version : 2.1
orbs:
 node: circleci/node@4.1.0
 aws-cli: circleci/aws-cli@2.0.3
 eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
 build: 
  docker:
   - image: "cimg/base:stable"
  steps:
   - node/install
   - node/install-yarn
   - checkout
   - aws-cli/setup
   - eb/setup
   - run : 
       name : Front-end install 
       command : cd .\udagram\udagram-frontend && npm install
   - run : 
       name : back-end install
       command: cd .\udagram\udagram-api && npm install
   
