version : 2.1
orbs:
 node : circleci/node@5.0.2
 AWS-CLI : circleci/aws-cli@3.1.1
jobs:
- image: "cimg/node:16.10"
  steps:
  - node/install
  - node/install-yarn
  - checkout
  - aws-cli/setup
  - eb/setup

  - run : 
   name : Front-end install 
   command : cd .\udagram\udagram-frontend && yarn 
  - run : back-end install
  command: cd .\udagram\udagram-api && yarn 
  

