version : 2.1
orbs:
 node: circleci/node@4.1.0
 aws-cli: circleci/aws-cli@2.0.3
 eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
 build: 
  docker:
   - image: "cimg/base:stable"
  environment:
   AWS_ACCESS_KEY_ID: AKIAU2EHTMQTLKQED5NK
   AWS_DEFAULT_REGION: us-east-1
   AWS_SECRET_ACCESS_KEY: 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
  steps:
   - node/install:
      node-version: "16.13.2"
   - node/install-yarn
   - checkout
   - aws-cli/setup
   - eb/setup
   - run : 
       name : Front-end install 
       command : yarn front-end-install
   - run : 
       name : back-end install
       command:  yarn back-end-install
   - run :
       name : back-end build
       command : yarn back-end-build
   - run :
       name : front-end build
       command : yarn front-end-build
   - run :
       name : front-end deploy
       command : yarn front-end-deploy
   - run :
       name : back-end deploy
       command : yarn back-end-deploy
